import type { JSX, ReactNode } from 'react';
import Link from 'next/link';

import type {
  MerchantDirectoryResult,
  MerchantDirectoryFilters,
} from '@/lib/types';
import { formatDateAr } from './display';
import { MerchantSummaryCard } from './MerchantSummaryCard';
import { PositiveEvidenceCard } from './PositiveEvidenceCard';
import { DirectoryFilterBar } from './DirectoryFilterBar';
import { Pagination, type QueryEntry } from './Pagination';

/**
 * Query entries preserved by pagination page links: the view plus every
 * active normalized filter, so paging never silently drops a filter. `page`
 * is regenerated by the Pagination component itself.
 */
function preservedQuery(
  view: 'all' | 'positive-evidence',
  filters: MerchantDirectoryFilters,
): QueryEntry[] {
  const entries: QueryEntry[] = [];
  if (view === 'positive-evidence') entries.push(['view', 'positive-evidence']);
  if (filters.category !== undefined) entries.push(['category', filters.category]);
  if (filters.governorate !== undefined) entries.push(['governorate', filters.governorate]);
  if (filters.coverage !== undefined) entries.push(['coverage', filters.coverage]);
  return entries;
}

/** Link to `page` on `basePath` preserving the normalized query. */
function pageHref(
  basePath: string,
  page: number,
  query: readonly QueryEntry[],
): string {
  const params = new URLSearchParams();
  for (const [key, value] of query) params.set(key, value);
  params.set('page', String(page));
  return `${basePath}?${params.toString()}`;
}

/**
 * Shared server-rendered shell for /merchants and /merchants/positive-evidence:
 * one heading block, one count/snapshot caption, one filter bar, one list of
 * shared cards, one accessible pagination. Pages pass copy + card kind — no
 * local ranking or duplicated card markup exists in the shell, and the page
 * links preserve every normalized filter parameter.
 */
export function DirectoryPageShell({
  title,
  intro,
  basePath,
  result,
  view,
  activeFilters,
  emptyState,
  cardKind,
  listLabel,
  extra,
}: {
  /** Page h1. */
  title: string;
  /** Explanatory paragraph(s) under the h1 (ordering/disclaimer copy). */
  intro: ReactNode;
  /** Route path for the filter form, reset link, and pagination links. */
  basePath: string;
  /** Selector result for the current normalized query. */
  result: MerchantDirectoryResult;
  /** 'all' | 'positive-evidence' — preserved across form submits and links. */
  view: 'all' | 'positive-evidence';
  /** Current normalized filters marking the selected options. */
  activeFilters: MerchantDirectoryFilters;
  /** Empty-state guidance when no sellers match the current filters. */
  emptyState: ReactNode;
  /** Which shared card renders each entry. */
  cardKind: 'summary' | 'positive';
  /** aria-label for the seller list. */
  listLabel: string;
  /** Optional page-specific block rendered between the filter bar and list. */
  extra?: ReactNode;
}): JSX.Element {
  const { pagination, availableFilters, snapshot } = result;
  const preserved = preservedQuery(view, activeFilters);
  return (
    <section className="flex w-full flex-col gap-6 py-8">
      <h1 className="text-2xl font-bold" dir="auto">
        {title}
      </h1>
      {intro}
      <p aria-live="polite">
        إجمالي البائعين المطابقين: <span dir="ltr">{pagination.total}</span> — تُعرض{' '}
        <span dir="ltr">{pagination.pageSize}</span> بائعًا في الصفحة.
      </p>
      <p className="text-sm">
        لقطة البيانات وُلِّدت في:{' '}
        <time dateTime={snapshot.generatedAt.slice(0, 10)} dir="ltr">
          {formatDateAr(snapshot.generatedAt)}
        </time>
      </p>
      <DirectoryFilterBar
        action={basePath}
        availableFilters={availableFilters}
        activeFilters={activeFilters}
      />
      {extra}
      {pagination.total === 0 ? (
        <div className="border border-black p-4">{emptyState}</div>
      ) : pagination.page > pagination.totalPages ? (
        <div className="border border-black p-4">
          <p>الصفحة المطلوبة خارج المدى.</p>
          <p className="mt-2 text-sm">
            إجمالي البائعين المطابقين <span dir="ltr">{pagination.total}</span>{' '}
            موزعين على <span dir="ltr">{pagination.totalPages}</span> صفحات.
          </p>
          <Link
            href={pageHref(basePath, pagination.totalPages, preserved)}
            className="mt-2 inline-block min-h-[44px] border border-black px-3 py-2 underline underline-offset-2"
          >
            الانتقال إلى الصفحة الأخيرة
          </Link>
        </div>
      ) : (
        <>
          <ul className="flex flex-col gap-4" aria-label={listLabel}>
            {result.items.map((entry) => (
              <li key={entry.id}>
                {cardKind === 'positive' ? (
                  <PositiveEvidenceCard entry={entry} />
                ) : (
                  <MerchantSummaryCard entry={entry} />
                )}
              </li>
            ))}
          </ul>
          <Pagination
            basePath={basePath}
            page={pagination.page}
            totalPages={pagination.totalPages}
            query={preserved}
          />
        </>
      )}
    </section>
  );
}
